SET(MATADOR_DB_LIBRARIES)

IF(ODBC_FOUND)
  MESSAGE(STATUS "Appending ODBC libs: ${ODBC_LIBRARY}")
  LIST(APPEND MATADOR_DB_LIBRARIES ${ODBC_LIBRARY})
ENDIF()

IF(MYSQL_FOUND)
  MESSAGE(STATUS "Appending MySQL libs: ${MYSQL_LIBRARY}")
  LIST(APPEND MATADOR_DB_LIBRARIES ${MYSQL_LIBRARY})
ENDIF()

IF(SQLITE3_FOUND)
  MESSAGE(STATUS "Appending SQLite3 libs: ${SQLITE3_LIBRARY}")
  LIST(APPEND MATADOR_DB_LIBRARIES ${SQLITE3_LIBRARY})
ENDIF()

IF(POSTGRESQL_FOUND)
  MESSAGE(STATUS "Appending PostgreSQL libs: ${POSTGRESQL_LIBRARIES}")
  LIST(APPEND MATADOR_DB_LIBRARIES ${POSTGRESQL_LIBRARIES})
ENDIF()